TOKENUNIV = '1479415334:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ownAPI = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' #Moscow
TOKENKUR = '1223627701:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
